### ISSUE TITLE
db_dir's format

### ISSUE THREAD

**Issue by cploveflower** [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing#12]
Hello!
@mnikitin 
I have read your paper,and now I want to achieve it，  but when I parper the dataset,I don't know the format  about the db_dir file，can you tell me about it or you can have a screeshot for your db_dir?I'm looking forward to your reply,thank you very much!

**Comment by mnikitin** [comment]
Hello @cploveflower !
If you are asking about this _db_dir_: https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/blob/master/crop_images.py#L58 ,
so in my case it has the following structure: https://www.dropbox.com/s/y6hzw5ch91db5tv/data_structure.png?dl=0 .
But you always can rewrite data preparation code for your way of data storing.

**Comment by cploveflower** [comment]
thank you for your reply! and I just begin the first step,and I have seen the picture that you gived me,I don't know what's the bboxes file,it's the txt file about the coordinate of face box or any other? I also want to know the data structure that you gived me is have been dealt with by crop_images or not,thank you!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mikhail Nikitin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 下午4:56
收件人:&nbsp;"mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing"<Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"Cpp"<1941750552@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing] db_dir's format (#12)




Hello @cploveflower !
 If you are asking about this db_dir: https://github.com/mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing/blob/master/crop_images.py#L58 ,
 so in my case it has the following structure: https://www.dropbox.com/s/y6hzw5ch91db5tv/data_structure.png?dl=0 .
 But you always can rewrite data preparation code for your way of data storing.

**Comment by mnikitin** [comment]
@cploveflower 
yes, _bboxes_ folder contains txt files with face bbox coordinates. You can also precompute bboxes and save them, or change the code to detect face bboxes in runtime.
And yes, the screenshot I shared presents the data structure appropriate to use with crop_images.py

**Comment by cploveflower** [comment]
It's kind of you!thank you for your help



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mikhail Nikitin"<notifications@github.com&gt;; 
发送时间: 2019年11月8日(星期五) 下午5:37
收件人: "mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing"<Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing@noreply.github.com&gt;; 
抄送: "Cpp"<1941750552@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing] db_dir&#39;s format (#12)




@cploveflower
 yes, bboxes folder contains txt files with face bbox coordinates. You can also precompute bboxes and save them, or change the code to detect face bboxes in runtime.
 And yes, the screenshot I shared presents the data structure appropriate to use with crop_images.py

**Comment by cploveflower** [comment]
Hello!
@mnikitin
I'm sorry to disturb you again,now I'm having a parpered for the box coordinate,and I want to know whether the x,y,w,h repersent the center coordinate,width and the height respectively
Thank you very much!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mikhail Nikitin"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月8日(星期五) 晚上6:05
收件人:&nbsp;"mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing"<Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing@noreply.github.com&gt;;
抄送:&nbsp;"Cpp"<1941750552@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [mnikitin/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing] db_dir's format (#12)




Closed #12.

**Comment by mnikitin** [comment]
@cploveflower 
x, y -- coordinates of the top left corner of face bbox
w, h -- width and height respectively

**Comment by cploveflower** [comment]
Hello!
@mnikitin 
because of your kind help，now I'm running the strat_train.py,
but there is a question about that:No module named 'net_generator',
I don't know whether it's due to the version of python,that I use python3,
do you have any suggestion about it?

**Comment by cploveflower** [comment]
hello!
@mnikitin 
Thank you for your kind help,now I'm running the start_train.py,but I meet some question like below,I use python3 and cpu-mxnet:
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x00000163A4E45EA0>
Traceback (most recent call last):
  File "C:\Users\cpp\AppData\Local\Programs\Python\Python35\lib\weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
time: 2.1069982051849365  count: 33000
time: 1.9469985961914062  count: 34000
time: 1.7679996490478516  count: 35000
[17:35:40] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_recordio_2.cc:170: ImageRecordIOParser2: E:\LCNN\data\casia/mxnet/scale_1.0__fold_1__train.rec, use 3 threads for decoding..
[17:35:42] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_recordio_2.cc:170: ImageRecordIOParser2: E:\LCNN\data\casia/mxnet/scale_1.0__fold_1__dev.rec, use 3 threads for decoding..
Traceback (most recent call last):
  File "E:/LCNN/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/start_train.py", line 75, in <module>
    main()
  File "E:/LCNN/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/start_train.py", line 70, in main
    train_net_casia('E:\LCNN\data\casia',float(scale),int(k))
  File "E:/LCNN/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/start_train.py", line 60, in train_net_casia
    start_experiment(config)
  File "E:/LCNN/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master/start_train.py", line 29, in start_experiment
    train_net(cfg)
  File "E:\LCNN\Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master\Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master\utils\net_train.py", line 10, in train_net
 cfg['input_shape'], cfg['batch_size'], cfg['data_params'])
  File "E:\LCNN\Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master\Learn-Convolutional-Neural-Network-for-Face-Anti-Spoofing-master\utils\net_utils.py", line 30, in get_rec_data_iterators
    mean_r=data_params['mean'][0], mean_g=data_params['mean'][1], mean_b=data_params['mean'][2])
  File "C:\Users\cpp\AppData\Local\Programs\Python\Python35\lib\site-packages\mxnet\io.py", line 936, in creator
    ctypes.byref(iter_handle)))
  File "C:\Users\cpp\AppData\Local\Programs\Python\Python35\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [17:35:42] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\input_split_base.cc:173: Check failed: files_.size() != 0U (0 vs. 0) Cannot find any files that matches the URI pattern E:\LCNN\data\casia/mxnet/scale_1.0__fold_1__dev.rec

**Comment by cploveflower** [comment]
Hello!
@mnikitin 
I have solved the question about the dev.rec question, but when I run the start_train.py again,It show the blow question:

Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x000002D78EEB5EA0>
Traceback (most recent call last):
  File "C:\Users\cpp\AppData\Local\Programs\Python\Python35\lib\weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
[16:15:41] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_recordio_2.cc:170: ImageRecordIOParser2: E:\LCNN\data\casia/mxnet/scale_1.0__fold_1__train.rec, use 3 threads for decoding..
[16:15:41] C:\Jenkins\workspace\mxnet-tag\mxnet\src\io\iter_image_recordio_2.cc:170: ImageRecordIOParser2: E:\LCNN\data\casia/mxnet/scale_1.0__fold_1__dev.rec, use 3 threads for decoding..

I don't know why, I think I need help,this code that I have run in the windows

**Comment by mnikitin** [comment]
@cploveflower 
I haven't encountered such problem and from the presented stack trace I can't understand where the error occurs. Maybe something is wrong with data preparation, or with python version. 
Probably this can help you: https://github.com/ayufan-rock64/linux-build/issues/136#issuecomment-405592727
